# Generated by Django 4.2 on 2023-04-04 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marni', '0003_post_delete_article_delete_reporter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
