# Generated by Django 4.2.2 on 2023-06-14 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marni', '0008_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='email',
            new_name='password',
        ),
    ]
