# Generated by Django 4.1.4 on 2023-06-22 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marni', '0009_rename_email_utilisateur_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
